# ==============================================
#
# Плагин создан: Vilariqu
# Возникли баги или ошибки?
# Discord & Telegram: @vilariqu
#
# ==============================================
#           EnchantUpgrader Configuration
# ==============================================

# Включить масштабирование стоимости (true/false)
cost-scaling: true


# Настройки зачарований (максимальные уровни)
enchantments:
  # Инструменты
  efficiency: 10
  silk_touch: 1
  fortune: 8
  unbreaking: 8
  
  # Оружие
  sharpness: 12
  smite: 10
  bane_of_arthropods: 10
  knockback: 5
  fire_aspect: 4
  looting: 6
  sweeping: 5
  
  # Броня
  protection: 10
  fire_protection: 8
  blast_protection: 8
  projectile_protection: 8
  feather_falling: 6
  thorns: 5
  depth_strider: 5
  frost_walker: 4
  mending: 1
  
  # Луки
  power: 8
  punch: 4
  flame: 1
  infinity: 1
  
  # Арбалеты
  piercing: 8
  multishot: 1
  quick_charge: 5
  
  # Трезубцы
  loyalty: 5
  riptide: 5
  channeling: 1
  impaling: 8

  # Другие
  soul_speed: 5
  swift_sneak: 5
  
# ==============================================
#        Конец конфигурации
# ==============================================
# Спасибо за использование плагина!
# ==============================================